// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C_A_LoginRequest struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	AccountName      *string  `protobuf:"bytes,2,req,name=AccountName" json:"AccountName,omitempty"`
	BuildNo          *string  `protobuf:"bytes,3,req,name=BuildNo" json:"BuildNo,omitempty"`
	SocketId         *int32   `protobuf:"varint,4,req,name=SocketId" json:"SocketId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_A_LoginRequest) Reset()                    { *m = C_A_LoginRequest{} }
func (m *C_A_LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*C_A_LoginRequest) ProtoMessage()               {}
func (*C_A_LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *C_A_LoginRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_A_LoginRequest) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

func (m *C_A_LoginRequest) GetBuildNo() string {
	if m != nil && m.BuildNo != nil {
		return *m.BuildNo
	}
	return ""
}

func (m *C_A_LoginRequest) GetSocketId() int32 {
	if m != nil && m.SocketId != nil {
		return *m.SocketId
	}
	return 0
}

type C_A_LoginRequest1 struct {
	Login            *C_A_LoginRequest `protobuf:"bytes,1,req,name=Login" json:"Login,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *C_A_LoginRequest1) Reset()                    { *m = C_A_LoginRequest1{} }
func (m *C_A_LoginRequest1) String() string            { return proto.CompactTextString(m) }
func (*C_A_LoginRequest1) ProtoMessage()               {}
func (*C_A_LoginRequest1) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *C_A_LoginRequest1) GetLogin() *C_A_LoginRequest {
	if m != nil {
		return m.Login
	}
	return nil
}

type C_A_RegisterRequest struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	AccountName      *string  `protobuf:"bytes,2,req,name=AccountName" json:"AccountName,omitempty"`
	SocketId         *int32   `protobuf:"varint,3,req,name=SocketId" json:"SocketId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_A_RegisterRequest) Reset()                    { *m = C_A_RegisterRequest{} }
func (m *C_A_RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*C_A_RegisterRequest) ProtoMessage()               {}
func (*C_A_RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *C_A_RegisterRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_A_RegisterRequest) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

func (m *C_A_RegisterRequest) GetSocketId() int32 {
	if m != nil && m.SocketId != nil {
		return *m.SocketId
	}
	return 0
}

type C_W_CreatePlayerRequest struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	PlayerName       *string  `protobuf:"bytes,2,req,name=PlayerName" json:"PlayerName,omitempty"`
	Sex              *int32   `protobuf:"varint,3,req,name=Sex" json:"Sex,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_W_CreatePlayerRequest) Reset()                    { *m = C_W_CreatePlayerRequest{} }
func (m *C_W_CreatePlayerRequest) String() string            { return proto.CompactTextString(m) }
func (*C_W_CreatePlayerRequest) ProtoMessage()               {}
func (*C_W_CreatePlayerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *C_W_CreatePlayerRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_CreatePlayerRequest) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *C_W_CreatePlayerRequest) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

type C_W_Game_LoginRequset struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	PlayerId         *int32   `protobuf:"varint,2,req,name=PlayerId" json:"PlayerId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_W_Game_LoginRequset) Reset()                    { *m = C_W_Game_LoginRequset{} }
func (m *C_W_Game_LoginRequset) String() string            { return proto.CompactTextString(m) }
func (*C_W_Game_LoginRequset) ProtoMessage()               {}
func (*C_W_Game_LoginRequset) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *C_W_Game_LoginRequset) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_Game_LoginRequset) GetPlayerId() int32 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type C_G_LogoutResponse struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_G_LogoutResponse) Reset()                    { *m = C_G_LogoutResponse{} }
func (m *C_G_LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*C_G_LogoutResponse) ProtoMessage()               {}
func (*C_G_LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *C_G_LogoutResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

type C_W_ChatMessage struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	Sender           *int32   `protobuf:"varint,2,req,name=Sender" json:"Sender,omitempty"`
	Recver           *int32   `protobuf:"varint,3,req,name=Recver" json:"Recver,omitempty"`
	MessageType      *int32   `protobuf:"varint,4,req,name=MessageType" json:"MessageType,omitempty"`
	Message          *string  `protobuf:"bytes,5,req,name=Message" json:"Message,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *C_W_ChatMessage) Reset()                    { *m = C_W_ChatMessage{} }
func (m *C_W_ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*C_W_ChatMessage) ProtoMessage()               {}
func (*C_W_ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *C_W_ChatMessage) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_ChatMessage) GetSender() int32 {
	if m != nil && m.Sender != nil {
		return *m.Sender
	}
	return 0
}

func (m *C_W_ChatMessage) GetRecver() int32 {
	if m != nil && m.Recver != nil {
		return *m.Recver
	}
	return 0
}

func (m *C_W_ChatMessage) GetMessageType() int32 {
	if m != nil && m.MessageType != nil {
		return *m.MessageType
	}
	return 0
}

func (m *C_W_ChatMessage) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*C_A_LoginRequest)(nil), "message.C_A_LoginRequest")
	proto.RegisterType((*C_A_LoginRequest1)(nil), "message.C_A_LoginRequest1")
	proto.RegisterType((*C_A_RegisterRequest)(nil), "message.C_A_RegisterRequest")
	proto.RegisterType((*C_W_CreatePlayerRequest)(nil), "message.C_W_CreatePlayerRequest")
	proto.RegisterType((*C_W_Game_LoginRequset)(nil), "message.C_W_Game_LoginRequset")
	proto.RegisterType((*C_G_LogoutResponse)(nil), "message.C_G_LogoutResponse")
	proto.RegisterType((*C_W_ChatMessage)(nil), "message.C_W_ChatMessage")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xcd, 0x4e, 0xf3, 0x30,
	0x10, 0x54, 0xd2, 0x2f, 0x5f, 0xcb, 0x16, 0x44, 0x31, 0x02, 0x42, 0x0f, 0x28, 0xca, 0xa9, 0xa7,
	0xf2, 0xf3, 0x06, 0x25, 0x88, 0x52, 0x09, 0xaa, 0xca, 0x45, 0xe2, 0x18, 0x59, 0xc9, 0xaa, 0x44,
	0xb4, 0x71, 0x88, 0x1d, 0x44, 0x0f, 0x1c, 0x79, 0x0b, 0xde, 0x81, 0x57, 0x44, 0x4e, 0xdc, 0x62,
	0xe5, 0x46, 0x11, 0x37, 0xcf, 0xec, 0x64, 0x67, 0x76, 0xb3, 0xb0, 0x1d, 0xcd, 0x13, 0x4c, 0x65,
	0x3f, 0xcb, 0xb9, 0xe4, 0xa4, 0xb9, 0x40, 0x21, 0xd8, 0x0c, 0xbb, 0x3b, 0xfa, 0x51, 0xf1, 0xfe,
	0x87, 0x05, 0x9d, 0x20, 0x1c, 0x84, 0xb7, 0x7c, 0x96, 0xa4, 0x14, 0x9f, 0x0b, 0x14, 0x92, 0x9c,
	0x01, 0x4c, 0x58, 0xf4, 0x84, 0xf2, 0x06, 0x59, 0xec, 0x5a, 0x9e, 0xdd, 0x6b, 0x5f, 0x74, 0xfa,
	0xab, 0x0f, 0x47, 0x59, 0x59, 0xa3, 0x86, 0x86, 0x78, 0xd0, 0x1e, 0x44, 0x11, 0x2f, 0x52, 0x39,
	0x66, 0x0b, 0x74, 0x6d, 0xcf, 0xee, 0x6d, 0x51, 0x93, 0x22, 0x2e, 0x34, 0x2f, 0x8b, 0x64, 0x1e,
	0x8f, 0xb9, 0xdb, 0x28, 0xab, 0x2b, 0x48, 0xba, 0xd0, 0x9a, 0x72, 0xd5, 0x69, 0x14, 0xbb, 0xff,
	0x3c, 0xbb, 0xe7, 0xd0, 0x35, 0xf6, 0xaf, 0x60, 0xaf, 0x9e, 0xee, 0x9c, 0x9c, 0x82, 0x53, 0x12,
	0x3a, 0xd9, 0xf1, 0x3a, 0x59, 0x5d, 0x4a, 0x2b, 0x9d, 0xff, 0x6e, 0xc1, 0xbe, 0xaa, 0x51, 0x9c,
	0x25, 0x42, 0x62, 0xfe, 0x97, 0x73, 0x9a, 0xd3, 0x34, 0x6a, 0xd3, 0xbc, 0xc1, 0x51, 0x10, 0x3e,
	0x84, 0x41, 0x8e, 0x4c, 0xe2, 0x64, 0xce, 0x96, 0xbf, 0x89, 0x72, 0x02, 0x50, 0xb5, 0x30, 0x92,
	0x18, 0x0c, 0xe9, 0x40, 0x63, 0x8a, 0xaf, 0x3a, 0x83, 0x7a, 0xfa, 0x08, 0x07, 0xca, 0x7e, 0xc8,
	0x16, 0xf8, 0xbd, 0x26, 0x81, 0x9b, 0x98, 0x77, 0xa1, 0x55, 0x59, 0x8d, 0xe2, 0xd2, 0xda, 0xa1,
	0x6b, 0xec, 0x5f, 0x03, 0x09, 0xc2, 0xa1, 0x72, 0xe0, 0x85, 0xa4, 0x28, 0x32, 0x9e, 0x0a, 0xfc,
	0xb9, 0x87, 0xff, 0x69, 0xc1, 0x6e, 0xb9, 0xae, 0x47, 0x26, 0xef, 0x2a, 0xdd, 0x06, 0x49, 0x0f,
	0xe1, 0xff, 0x14, 0xd3, 0x18, 0x73, 0x9d, 0x53, 0x23, 0xc5, 0x53, 0x8c, 0x5e, 0x30, 0xd7, 0x1b,
	0xd2, 0x48, 0xfd, 0x61, 0x6d, 0x76, 0xbf, 0xcc, 0x50, 0x1f, 0xa4, 0x49, 0xa9, 0x4b, 0xd6, 0xd0,
	0x75, 0xaa, 0x4b, 0xd6, 0xf0, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x53, 0xcf, 0xe3, 0x59, 0x73, 0x03,
	0x00, 0x00,
}
