// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

/*
Package message is a generated protocol buffer package.

It is generated from these files:
	message.proto
	client.proto
	game.proto

It has these top-level messages:
	Ipacket
	PlayerData
	W_C_CreatePlayerResponse
	W_C_SelectPlayerResponse
	A_C_RegisterResponse
	A_C_LoginRequest
	C_A_LoginRequest
	C_A_LoginRequest1
	C_A_RegisterRequest
	C_W_CreatePlayerRequest
	C_W_Game_LoginRequset
	C_G_LogoutResponse
	C_W_ChatMessage
	W_C_ChatMessage
	Point3F
	C_W_Move
	W_C_LoginMap
	W_C_Move
	W_C_ADD_SIMOBJ
	C_W_LoginCopyMap
*/
package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SERVICE int32

const (
	SERVICE_NONE          SERVICE = 0
	SERVICE_CLIENT        SERVICE = 1
	SERVICE_GATESERVER    SERVICE = 2
	SERVICE_ACCOUNTSERVER SERVICE = 3
	SERVICE_WORLDSERVER   SERVICE = 4
	SERVICE_MONITORSERVER SERVICE = 5
)

var SERVICE_name = map[int32]string{
	0: "NONE",
	1: "CLIENT",
	2: "GATESERVER",
	3: "ACCOUNTSERVER",
	4: "WORLDSERVER",
	5: "MONITORSERVER",
}
var SERVICE_value = map[string]int32{
	"NONE":          0,
	"CLIENT":        1,
	"GATESERVER":    2,
	"ACCOUNTSERVER": 3,
	"WORLDSERVER":   4,
	"MONITORSERVER": 5,
}

func (x SERVICE) Enum() *SERVICE {
	p := new(SERVICE)
	*p = x
	return p
}
func (x SERVICE) String() string {
	return proto.EnumName(SERVICE_name, int32(x))
}
func (x *SERVICE) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SERVICE_value, data, "SERVICE")
	if err != nil {
		return err
	}
	*x = SERVICE(value)
	return nil
}
func (SERVICE) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type CHAT int32

const (
	CHAT_MSG_TYPE_WORLD   CHAT = 0
	CHAT_MSG_TYPE_PRIVATE CHAT = 1
	CHAT_MSG_TYPE_ORG     CHAT = 2
	CHAT_MSG_TYPE_COUNT   CHAT = 3
)

var CHAT_name = map[int32]string{
	0: "MSG_TYPE_WORLD",
	1: "MSG_TYPE_PRIVATE",
	2: "MSG_TYPE_ORG",
	3: "MSG_TYPE_COUNT",
}
var CHAT_value = map[string]int32{
	"MSG_TYPE_WORLD":   0,
	"MSG_TYPE_PRIVATE": 1,
	"MSG_TYPE_ORG":     2,
	"MSG_TYPE_COUNT":   3,
}

func (x CHAT) Enum() *CHAT {
	p := new(CHAT)
	*p = x
	return p
}
func (x CHAT) String() string {
	return proto.EnumName(CHAT_name, int32(x))
}
func (x *CHAT) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CHAT_value, data, "CHAT")
	if err != nil {
		return err
	}
	*x = CHAT(value)
	return nil
}
func (CHAT) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Ipacket struct {
	Stx              *int32 `protobuf:"varint,1,req,name=Stx,def=39" json:"Stx,omitempty"`
	DestServerType   *int32 `protobuf:"varint,2,req,name=DestServerType" json:"DestServerType,omitempty"`
	Ckx              *int32 `protobuf:"varint,3,req,name=Ckx,def=114" json:"Ckx,omitempty"`
	Id               *int64 `protobuf:"varint,4,req,name=Id" json:"Id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Ipacket) Reset()                    { *m = Ipacket{} }
func (m *Ipacket) String() string            { return proto.CompactTextString(m) }
func (*Ipacket) ProtoMessage()               {}
func (*Ipacket) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

const Default_Ipacket_Stx int32 = 39
const Default_Ipacket_Ckx int32 = 114

func (m *Ipacket) GetStx() int32 {
	if m != nil && m.Stx != nil {
		return *m.Stx
	}
	return Default_Ipacket_Stx
}

func (m *Ipacket) GetDestServerType() int32 {
	if m != nil && m.DestServerType != nil {
		return *m.DestServerType
	}
	return 0
}

func (m *Ipacket) GetCkx() int32 {
	if m != nil && m.Ckx != nil {
		return *m.Ckx
	}
	return Default_Ipacket_Ckx
}

func (m *Ipacket) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

type PlayerData struct {
	PlayerID         *int64  `protobuf:"varint,1,req,name=PlayerID" json:"PlayerID,omitempty"`
	PlayerName       *string `protobuf:"bytes,2,req,name=PlayerName" json:"PlayerName,omitempty"`
	PlayerGold       *int32  `protobuf:"varint,3,req,name=PlayerGold" json:"PlayerGold,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *PlayerData) Reset()                    { *m = PlayerData{} }
func (m *PlayerData) String() string            { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()               {}
func (*PlayerData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PlayerData) GetPlayerID() int64 {
	if m != nil && m.PlayerID != nil {
		return *m.PlayerID
	}
	return 0
}

func (m *PlayerData) GetPlayerName() string {
	if m != nil && m.PlayerName != nil {
		return *m.PlayerName
	}
	return ""
}

func (m *PlayerData) GetPlayerGold() int32 {
	if m != nil && m.PlayerGold != nil {
		return *m.PlayerGold
	}
	return 0
}

type W_C_CreatePlayerResponse struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	Error            *int32   `protobuf:"varint,2,req,name=Error" json:"Error,omitempty"`
	PlayerId         *int64   `protobuf:"varint,3,req,name=PlayerId" json:"PlayerId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *W_C_CreatePlayerResponse) Reset()                    { *m = W_C_CreatePlayerResponse{} }
func (m *W_C_CreatePlayerResponse) String() string            { return proto.CompactTextString(m) }
func (*W_C_CreatePlayerResponse) ProtoMessage()               {}
func (*W_C_CreatePlayerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *W_C_CreatePlayerResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *W_C_CreatePlayerResponse) GetError() int32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func (m *W_C_CreatePlayerResponse) GetPlayerId() int64 {
	if m != nil && m.PlayerId != nil {
		return *m.PlayerId
	}
	return 0
}

type W_C_SelectPlayerResponse struct {
	PacketHead       *Ipacket      `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	AccountId        *int64        `protobuf:"varint,2,req,name=AccountId" json:"AccountId,omitempty"`
	PlayerData       []*PlayerData `protobuf:"bytes,3,rep,name=PlayerData" json:"PlayerData,omitempty"`
	XXX_unrecognized []byte        `json:"-"`
}

func (m *W_C_SelectPlayerResponse) Reset()                    { *m = W_C_SelectPlayerResponse{} }
func (m *W_C_SelectPlayerResponse) String() string            { return proto.CompactTextString(m) }
func (*W_C_SelectPlayerResponse) ProtoMessage()               {}
func (*W_C_SelectPlayerResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *W_C_SelectPlayerResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *W_C_SelectPlayerResponse) GetAccountId() int64 {
	if m != nil && m.AccountId != nil {
		return *m.AccountId
	}
	return 0
}

func (m *W_C_SelectPlayerResponse) GetPlayerData() []*PlayerData {
	if m != nil {
		return m.PlayerData
	}
	return nil
}

type A_C_RegisterResponse struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	Error            *int32   `protobuf:"varint,2,req,name=Error" json:"Error,omitempty"`
	SocketId         *int32   `protobuf:"varint,3,req,name=SocketId" json:"SocketId,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *A_C_RegisterResponse) Reset()                    { *m = A_C_RegisterResponse{} }
func (m *A_C_RegisterResponse) String() string            { return proto.CompactTextString(m) }
func (*A_C_RegisterResponse) ProtoMessage()               {}
func (*A_C_RegisterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *A_C_RegisterResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *A_C_RegisterResponse) GetError() int32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func (m *A_C_RegisterResponse) GetSocketId() int32 {
	if m != nil && m.SocketId != nil {
		return *m.SocketId
	}
	return 0
}

type A_C_LoginRequest struct {
	PacketHead       *Ipacket `protobuf:"bytes,1,req,name=PacketHead" json:"PacketHead,omitempty"`
	Error            *int32   `protobuf:"varint,2,req,name=Error" json:"Error,omitempty"`
	SocketId         *int32   `protobuf:"varint,3,req,name=SocketId" json:"SocketId,omitempty"`
	AccountName      *string  `protobuf:"bytes,4,req,name=AccountName" json:"AccountName,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *A_C_LoginRequest) Reset()                    { *m = A_C_LoginRequest{} }
func (m *A_C_LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*A_C_LoginRequest) ProtoMessage()               {}
func (*A_C_LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *A_C_LoginRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *A_C_LoginRequest) GetError() int32 {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return 0
}

func (m *A_C_LoginRequest) GetSocketId() int32 {
	if m != nil && m.SocketId != nil {
		return *m.SocketId
	}
	return 0
}

func (m *A_C_LoginRequest) GetAccountName() string {
	if m != nil && m.AccountName != nil {
		return *m.AccountName
	}
	return ""
}

func init() {
	proto.RegisterType((*Ipacket)(nil), "message.Ipacket")
	proto.RegisterType((*PlayerData)(nil), "message.PlayerData")
	proto.RegisterType((*W_C_CreatePlayerResponse)(nil), "message.W_C_CreatePlayerResponse")
	proto.RegisterType((*W_C_SelectPlayerResponse)(nil), "message.W_C_SelectPlayerResponse")
	proto.RegisterType((*A_C_RegisterResponse)(nil), "message.A_C_RegisterResponse")
	proto.RegisterType((*A_C_LoginRequest)(nil), "message.A_C_LoginRequest")
	proto.RegisterEnum("message.SERVICE", SERVICE_name, SERVICE_value)
	proto.RegisterEnum("message.CHAT", CHAT_name, CHAT_value)
}

func init() { proto.RegisterFile("message.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 470 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0x4f, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0x6b, 0xaf, 0x43, 0xda, 0x09, 0x0d, 0xcb, 0x10, 0x24, 0x0b, 0x21, 0x14, 0xf9, 0x80,
	0xa2, 0x1e, 0x2a, 0xda, 0x72, 0x81, 0x9b, 0xe5, 0x58, 0xe9, 0x4a, 0xa9, 0x1d, 0x8d, 0x4d, 0x2a,
	0x4e, 0x96, 0x15, 0x2f, 0xa1, 0x6a, 0x1a, 0x07, 0x7b, 0x8b, 0x1a, 0x0e, 0x7c, 0x0e, 0x6e, 0x7c,
	0x55, 0xe4, 0x3f, 0x71, 0x0c, 0x57, 0x04, 0xc7, 0xf7, 0xdb, 0x37, 0x7e, 0x6f, 0xc7, 0x0b, 0xc7,
	0x77, 0x32, 0xcf, 0xe3, 0xa5, 0x3c, 0xdd, 0x64, 0xa9, 0x4a, 0xb1, 0x5b, 0x4b, 0x6b, 0x0d, 0x5d,
	0xb1, 0x89, 0x17, 0xb7, 0x52, 0xe1, 0x00, 0x58, 0xa0, 0x1e, 0x4c, 0x6d, 0xa8, 0x8f, 0x3a, 0xef,
	0xf5, 0x8b, 0x77, 0x54, 0x48, 0x7c, 0x0d, 0xfd, 0xb1, 0xcc, 0x55, 0x20, 0xb3, 0xaf, 0x32, 0x0b,
	0xb7, 0x1b, 0x69, 0xea, 0x85, 0x81, 0xfe, 0xa0, 0xf8, 0x1c, 0x98, 0x73, 0xfb, 0x60, 0xb2, 0x72,
	0x9a, 0x9d, 0x9d, 0xbd, 0xa5, 0x42, 0x63, 0x1f, 0x74, 0x91, 0x98, 0xc6, 0x50, 0x1f, 0x31, 0xd2,
	0x45, 0x62, 0x7d, 0x06, 0x98, 0xad, 0xe2, 0xad, 0xcc, 0xc6, 0xb1, 0x8a, 0xf1, 0x05, 0x1c, 0x56,
	0x4a, 0x8c, 0xcb, 0x5c, 0x46, 0x8d, 0xc6, 0x57, 0x3b, 0xa7, 0x17, 0xdf, 0x55, 0xa1, 0x47, 0xd4,
	0x22, 0xfb, 0xf3, 0x49, 0xba, 0x4a, 0xaa, 0x5c, 0x6a, 0x11, 0xeb, 0x3b, 0x98, 0xd7, 0x91, 0x13,
	0x39, 0x99, 0x8c, 0x95, 0xac, 0x38, 0xc9, 0x7c, 0x93, 0xae, 0x73, 0x89, 0x6f, 0x00, 0x66, 0xe5,
	0xa5, 0x2f, 0x65, 0x9c, 0x94, 0xc9, 0xbd, 0x73, 0x7e, 0xba, 0x5b, 0x51, 0xbd, 0x10, 0x6a, 0x79,
	0x70, 0x00, 0x1d, 0x37, 0xcb, 0xd2, 0xac, 0xbe, 0x7d, 0x25, 0x5a, 0xfd, 0xab, 0x06, 0xfb, 0xfe,
	0x89, 0xf5, 0x53, 0xab, 0x0a, 0x04, 0x72, 0x25, 0x17, 0xea, 0xaf, 0x0b, 0xbc, 0x84, 0x23, 0x7b,
	0xb1, 0x48, 0xef, 0xd7, 0x4a, 0x24, 0x65, 0x09, 0x46, 0x7b, 0x80, 0x17, 0xed, 0xb5, 0x9a, 0x6c,
	0xc8, 0x46, 0xbd, 0xf3, 0x67, 0xcd, 0xf7, 0xf6, 0x47, 0xd4, 0xb2, 0x59, 0xdf, 0x60, 0x60, 0x47,
	0x4e, 0x44, 0x72, 0x79, 0x93, 0xab, 0x7f, 0xb3, 0x9d, 0x20, 0x2d, 0x3c, 0x62, 0xf7, 0x7f, 0x1a,
	0x6d, 0xfd, 0xd0, 0x80, 0x17, 0xe1, 0xd3, 0x74, 0x79, 0xb3, 0x26, 0xf9, 0xe5, 0x5e, 0xe6, 0xea,
	0x7f, 0x04, 0xe3, 0x10, 0x7a, 0xf5, 0xda, 0xca, 0x77, 0x65, 0x94, 0xef, 0xaa, 0x8d, 0x4e, 0x3e,
	0x41, 0x37, 0x70, 0x69, 0x2e, 0x1c, 0x17, 0x0f, 0xc1, 0xf0, 0x7c, 0xcf, 0xe5, 0x07, 0x08, 0xf0,
	0xc8, 0x99, 0x0a, 0xd7, 0x0b, 0xb9, 0x86, 0x7d, 0x80, 0x89, 0x1d, 0xba, 0x85, 0xc9, 0x25, 0xae,
	0xe3, 0x53, 0x38, 0xb6, 0x1d, 0xc7, 0xff, 0xe0, 0x85, 0x35, 0x62, 0xf8, 0x04, 0x7a, 0xd7, 0x3e,
	0x4d, 0xc7, 0x35, 0x30, 0x0a, 0xcf, 0x95, 0xef, 0x89, 0xd0, 0xa7, 0x1a, 0x75, 0x4e, 0xe6, 0x60,
	0x38, 0x97, 0x76, 0x88, 0x08, 0xfd, 0xab, 0x60, 0x12, 0x85, 0x1f, 0x67, 0x6e, 0x54, 0x0e, 0xf1,
	0x03, 0x1c, 0x00, 0x6f, 0xd8, 0x8c, 0xc4, 0xdc, 0x0e, 0x5d, 0xae, 0x21, 0x87, 0xc7, 0x0d, 0xf5,
	0x69, 0xc2, 0xf5, 0xdf, 0x66, 0xcb, 0x06, 0x9c, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xee, 0x0b,
	0xc7, 0x01, 0xeb, 0x03, 0x00, 0x00,
}
