// Code generated by protoc-gen-go. DO NOT EDIT.
// source: client.proto

package message

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type C_A_LoginRequest struct {
	PacketHead  *Ipacket `protobuf:"bytes,1,opt,name=PacketHead" json:"PacketHead,omitempty"`
	AccountName string   `protobuf:"bytes,2,opt,name=AccountName" json:"AccountName,omitempty"`
	BuildNo     string   `protobuf:"bytes,3,opt,name=BuildNo" json:"BuildNo,omitempty"`
	SocketId    int32    `protobuf:"varint,4,opt,name=SocketId" json:"SocketId,omitempty"`
}

func (m *C_A_LoginRequest) Reset()                    { *m = C_A_LoginRequest{} }
func (m *C_A_LoginRequest) String() string            { return proto.CompactTextString(m) }
func (*C_A_LoginRequest) ProtoMessage()               {}
func (*C_A_LoginRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *C_A_LoginRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_A_LoginRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *C_A_LoginRequest) GetBuildNo() string {
	if m != nil {
		return m.BuildNo
	}
	return ""
}

func (m *C_A_LoginRequest) GetSocketId() int32 {
	if m != nil {
		return m.SocketId
	}
	return 0
}

type C_A_LoginRequest1 struct {
	Login *C_A_LoginRequest `protobuf:"bytes,1,opt,name=Login" json:"Login,omitempty"`
}

func (m *C_A_LoginRequest1) Reset()                    { *m = C_A_LoginRequest1{} }
func (m *C_A_LoginRequest1) String() string            { return proto.CompactTextString(m) }
func (*C_A_LoginRequest1) ProtoMessage()               {}
func (*C_A_LoginRequest1) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *C_A_LoginRequest1) GetLogin() *C_A_LoginRequest {
	if m != nil {
		return m.Login
	}
	return nil
}

type C_A_RegisterRequest struct {
	PacketHead  *Ipacket `protobuf:"bytes,1,opt,name=PacketHead" json:"PacketHead,omitempty"`
	AccountName string   `protobuf:"bytes,2,opt,name=AccountName" json:"AccountName,omitempty"`
	SocketId    int32    `protobuf:"varint,3,opt,name=SocketId" json:"SocketId,omitempty"`
}

func (m *C_A_RegisterRequest) Reset()                    { *m = C_A_RegisterRequest{} }
func (m *C_A_RegisterRequest) String() string            { return proto.CompactTextString(m) }
func (*C_A_RegisterRequest) ProtoMessage()               {}
func (*C_A_RegisterRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *C_A_RegisterRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_A_RegisterRequest) GetAccountName() string {
	if m != nil {
		return m.AccountName
	}
	return ""
}

func (m *C_A_RegisterRequest) GetSocketId() int32 {
	if m != nil {
		return m.SocketId
	}
	return 0
}

type C_W_CreatePlayerRequest struct {
	PacketHead *Ipacket `protobuf:"bytes,1,opt,name=PacketHead" json:"PacketHead,omitempty"`
	PlayerName string   `protobuf:"bytes,2,opt,name=PlayerName" json:"PlayerName,omitempty"`
	Sex        int32    `protobuf:"varint,3,opt,name=Sex" json:"Sex,omitempty"`
}

func (m *C_W_CreatePlayerRequest) Reset()                    { *m = C_W_CreatePlayerRequest{} }
func (m *C_W_CreatePlayerRequest) String() string            { return proto.CompactTextString(m) }
func (*C_W_CreatePlayerRequest) ProtoMessage()               {}
func (*C_W_CreatePlayerRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *C_W_CreatePlayerRequest) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_CreatePlayerRequest) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *C_W_CreatePlayerRequest) GetSex() int32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

type C_W_Game_LoginRequset struct {
	PacketHead *Ipacket `protobuf:"bytes,1,opt,name=PacketHead" json:"PacketHead,omitempty"`
	PlayerId   int64    `protobuf:"varint,2,opt,name=PlayerId" json:"PlayerId,omitempty"`
}

func (m *C_W_Game_LoginRequset) Reset()                    { *m = C_W_Game_LoginRequset{} }
func (m *C_W_Game_LoginRequset) String() string            { return proto.CompactTextString(m) }
func (*C_W_Game_LoginRequset) ProtoMessage()               {}
func (*C_W_Game_LoginRequset) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *C_W_Game_LoginRequset) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_Game_LoginRequset) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type C_G_LogoutResponse struct {
	PacketHead *Ipacket `protobuf:"bytes,1,opt,name=PacketHead" json:"PacketHead,omitempty"`
}

func (m *C_G_LogoutResponse) Reset()                    { *m = C_G_LogoutResponse{} }
func (m *C_G_LogoutResponse) String() string            { return proto.CompactTextString(m) }
func (*C_G_LogoutResponse) ProtoMessage()               {}
func (*C_G_LogoutResponse) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *C_G_LogoutResponse) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

type C_W_ChatMessage struct {
	PacketHead  *Ipacket `protobuf:"bytes,1,opt,name=PacketHead" json:"PacketHead,omitempty"`
	Sender      int64    `protobuf:"varint,2,opt,name=Sender" json:"Sender,omitempty"`
	Recver      int64    `protobuf:"varint,3,opt,name=Recver" json:"Recver,omitempty"`
	MessageType int32    `protobuf:"varint,4,opt,name=MessageType" json:"MessageType,omitempty"`
	Message     string   `protobuf:"bytes,5,opt,name=Message" json:"Message,omitempty"`
}

func (m *C_W_ChatMessage) Reset()                    { *m = C_W_ChatMessage{} }
func (m *C_W_ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*C_W_ChatMessage) ProtoMessage()               {}
func (*C_W_ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *C_W_ChatMessage) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *C_W_ChatMessage) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *C_W_ChatMessage) GetRecver() int64 {
	if m != nil {
		return m.Recver
	}
	return 0
}

func (m *C_W_ChatMessage) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *C_W_ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type W_C_ChatMessage struct {
	PacketHead  *Ipacket `protobuf:"bytes,1,opt,name=PacketHead" json:"PacketHead,omitempty"`
	Sender      int64    `protobuf:"varint,2,opt,name=Sender" json:"Sender,omitempty"`
	SenderName  string   `protobuf:"bytes,3,opt,name=SenderName" json:"SenderName,omitempty"`
	Recver      int64    `protobuf:"varint,4,opt,name=Recver" json:"Recver,omitempty"`
	RecverName  string   `protobuf:"bytes,5,opt,name=RecverName" json:"RecverName,omitempty"`
	MessageType int32    `protobuf:"varint,6,opt,name=MessageType" json:"MessageType,omitempty"`
	Message     string   `protobuf:"bytes,7,opt,name=Message" json:"Message,omitempty"`
}

func (m *W_C_ChatMessage) Reset()                    { *m = W_C_ChatMessage{} }
func (m *W_C_ChatMessage) String() string            { return proto.CompactTextString(m) }
func (*W_C_ChatMessage) ProtoMessage()               {}
func (*W_C_ChatMessage) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *W_C_ChatMessage) GetPacketHead() *Ipacket {
	if m != nil {
		return m.PacketHead
	}
	return nil
}

func (m *W_C_ChatMessage) GetSender() int64 {
	if m != nil {
		return m.Sender
	}
	return 0
}

func (m *W_C_ChatMessage) GetSenderName() string {
	if m != nil {
		return m.SenderName
	}
	return ""
}

func (m *W_C_ChatMessage) GetRecver() int64 {
	if m != nil {
		return m.Recver
	}
	return 0
}

func (m *W_C_ChatMessage) GetRecverName() string {
	if m != nil {
		return m.RecverName
	}
	return ""
}

func (m *W_C_ChatMessage) GetMessageType() int32 {
	if m != nil {
		return m.MessageType
	}
	return 0
}

func (m *W_C_ChatMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type W_C_Test struct {
	Recv []int32 `protobuf:"varint,1,rep,packed,name=Recv" json:"Recv,omitempty"`
}

func (m *W_C_Test) Reset()                    { *m = W_C_Test{} }
func (m *W_C_Test) String() string            { return proto.CompactTextString(m) }
func (*W_C_Test) ProtoMessage()               {}
func (*W_C_Test) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{8} }

func (m *W_C_Test) GetRecv() []int32 {
	if m != nil {
		return m.Recv
	}
	return nil
}

func init() {
	proto.RegisterType((*C_A_LoginRequest)(nil), "message.C_A_LoginRequest")
	proto.RegisterType((*C_A_LoginRequest1)(nil), "message.C_A_LoginRequest1")
	proto.RegisterType((*C_A_RegisterRequest)(nil), "message.C_A_RegisterRequest")
	proto.RegisterType((*C_W_CreatePlayerRequest)(nil), "message.C_W_CreatePlayerRequest")
	proto.RegisterType((*C_W_Game_LoginRequset)(nil), "message.C_W_Game_LoginRequset")
	proto.RegisterType((*C_G_LogoutResponse)(nil), "message.C_G_LogoutResponse")
	proto.RegisterType((*C_W_ChatMessage)(nil), "message.C_W_ChatMessage")
	proto.RegisterType((*W_C_ChatMessage)(nil), "message.W_C_ChatMessage")
	proto.RegisterType((*W_C_Test)(nil), "message.W_C_Test")
}

func init() { proto.RegisterFile("client.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 426 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x54, 0xcb, 0x8e, 0xd3, 0x30,
	0x14, 0x95, 0x49, 0xd3, 0x96, 0x3b, 0xa0, 0x29, 0x46, 0x40, 0xe8, 0x22, 0x8a, 0xb2, 0xca, 0x6a,
	0x78, 0x7d, 0xc1, 0x10, 0xc4, 0x50, 0x09, 0x46, 0x23, 0xb7, 0x52, 0x97, 0x91, 0x49, 0xae, 0x4a,
	0x44, 0x1b, 0x87, 0xc4, 0x41, 0x74, 0xc1, 0x92, 0xbf, 0xe0, 0x1f, 0xf8, 0x34, 0x7e, 0x01, 0xf9,
	0xd1, 0xe2, 0x66, 0x81, 0x44, 0x47, 0xdd, 0xdd, 0x73, 0x7c, 0xed, 0x73, 0x8e, 0x7d, 0x13, 0xb8,
	0x97, 0xaf, 0x4b, 0xac, 0xe4, 0x45, 0xdd, 0x08, 0x29, 0xe8, 0x68, 0x83, 0x6d, 0xcb, 0x57, 0x38,
	0xbd, 0x6f, 0x0b, 0xc3, 0xc7, 0x3f, 0x09, 0x4c, 0xd2, 0xec, 0x32, 0x7b, 0x2f, 0x56, 0x65, 0xc5,
	0xf0, 0x4b, 0x87, 0xad, 0xa4, 0xcf, 0x01, 0x6e, 0x78, 0xfe, 0x19, 0xe5, 0x3b, 0xe4, 0x45, 0x40,
	0x22, 0x92, 0x9c, 0xbd, 0x9c, 0x5c, 0xec, 0x36, 0xce, 0x6a, 0xbd, 0xc6, 0x9c, 0x1e, 0x1a, 0xc1,
	0xd9, 0x65, 0x9e, 0x8b, 0xae, 0x92, 0xd7, 0x7c, 0x83, 0xc1, 0x9d, 0x88, 0x24, 0x77, 0x99, 0x4b,
	0xd1, 0x00, 0x46, 0xaf, 0xbb, 0x72, 0x5d, 0x5c, 0x8b, 0xc0, 0xd3, 0xab, 0x3b, 0x48, 0xa7, 0x30,
	0x9e, 0x0b, 0x75, 0xd2, 0xac, 0x08, 0x06, 0x11, 0x49, 0x7c, 0xb6, 0xc7, 0xf1, 0x1b, 0x78, 0xd0,
	0x77, 0xf7, 0x82, 0x3e, 0x03, 0x5f, 0x13, 0xd6, 0xd9, 0xd3, 0xbd, 0xb3, 0x7e, 0x2b, 0x33, 0x7d,
	0xf1, 0x0f, 0x02, 0x0f, 0xd5, 0x1a, 0xc3, 0x55, 0xd9, 0x4a, 0x6c, 0x4e, 0x99, 0xd3, 0x4d, 0xe3,
	0xf5, 0xd2, 0x7c, 0x87, 0x27, 0x69, 0xb6, 0xcc, 0xd2, 0x06, 0xb9, 0xc4, 0x9b, 0x35, 0xdf, 0xde,
	0xc6, 0x4a, 0x08, 0x60, 0x8e, 0x70, 0x9c, 0x38, 0x0c, 0x9d, 0x80, 0x37, 0xc7, 0x6f, 0xd6, 0x83,
	0x2a, 0x63, 0x84, 0x47, 0x4a, 0xfe, 0x8a, 0x6f, 0xf0, 0xef, 0x35, 0xb5, 0x78, 0x8c, 0xf8, 0x14,
	0xc6, 0x46, 0x6a, 0x56, 0x68, 0x69, 0x8f, 0xed, 0x71, 0xfc, 0x16, 0x68, 0x9a, 0x5d, 0x29, 0x05,
	0xd1, 0x49, 0x86, 0x6d, 0x2d, 0xaa, 0x16, 0xff, 0x5f, 0x23, 0xfe, 0x45, 0xe0, 0x5c, 0x5f, 0xd7,
	0x27, 0x2e, 0x3f, 0x98, 0xbe, 0x23, 0x9c, 0x3e, 0x86, 0xe1, 0x1c, 0xab, 0x02, 0x1b, 0xeb, 0xd3,
	0x22, 0xc5, 0x33, 0xcc, 0xbf, 0x62, 0xa3, 0x6f, 0xc8, 0x63, 0x16, 0xa9, 0x17, 0xb6, 0x62, 0x8b,
	0x6d, 0x8d, 0x76, 0x20, 0x5d, 0x4a, 0x4d, 0xb2, 0x85, 0x81, 0x6f, 0x26, 0xd9, 0xc2, 0xf8, 0x37,
	0x81, 0xf3, 0x65, 0x96, 0x9e, 0xc8, 0x71, 0x08, 0x60, 0x2a, 0xfd, 0xe0, 0xe6, 0x23, 0x72, 0x18,
	0x27, 0xd1, 0xe0, 0x20, 0x51, 0x08, 0x60, 0x2a, 0xbd, 0xcf, 0x58, 0x76, 0x98, 0x7e, 0xe2, 0xe1,
	0x3f, 0x13, 0x8f, 0x0e, 0x13, 0x87, 0x30, 0x56, 0x81, 0x17, 0x6a, 0x84, 0x29, 0x0c, 0xd4, 0xa9,
	0x01, 0x89, 0xbc, 0xc4, 0x67, 0xba, 0xfe, 0x38, 0xd4, 0x7f, 0x99, 0x57, 0x7f, 0x02, 0x00, 0x00,
	0xff, 0xff, 0x61, 0x45, 0x7d, 0x25, 0x8d, 0x04, 0x00, 0x00,
}
