// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.22.0
// 	protoc        v3.4.0
// source: game.proto

package message

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//point3F
type Point3F struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=X,proto3" json:"X,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=Y,proto3" json:"Y,omitempty"`
	Z float32 `protobuf:"fixed32,3,opt,name=Z,proto3" json:"Z,omitempty"`
}

func (x *Point3F) Reset() {
	*x = Point3F{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point3F) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point3F) ProtoMessage() {}

func (x *Point3F) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point3F.ProtoReflect.Descriptor instead.
func (*Point3F) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *Point3F) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point3F) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *Point3F) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

//移动包
type C_Z_Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *Ipacket       `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Move       *C_Z_Move_Move `protobuf:"bytes,2,opt,name=move,proto3" json:"move,omitempty"`
}

func (x *C_Z_Move) Reset() {
	*x = C_Z_Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_Move) ProtoMessage() {}

func (x *C_Z_Move) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_Move.ProtoReflect.Descriptor instead.
func (*C_Z_Move) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *C_Z_Move) GetPacketHead() *Ipacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *C_Z_Move) GetMove() *C_Z_Move_Move {
	if x != nil {
		return x.Move
	}
	return nil
}

//skill
type C_Z_Skill struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	SkillId    int32    `protobuf:"varint,2,opt,name=SkillId,proto3" json:"SkillId,omitempty"`
	TargetId   int64    `protobuf:"varint,3,opt,name=TargetId,proto3" json:"TargetId,omitempty"`
}

func (x *C_Z_Skill) Reset() {
	*x = C_Z_Skill{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_Skill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_Skill) ProtoMessage() {}

func (x *C_Z_Skill) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_Skill.ProtoReflect.Descriptor instead.
func (*C_Z_Skill) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{2}
}

func (x *C_Z_Skill) GetPacketHead() *Ipacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *C_Z_Skill) GetSkillId() int32 {
	if x != nil {
		return x.SkillId
	}
	return 0
}

func (x *C_Z_Skill) GetTargetId() int64 {
	if x != nil {
		return x.TargetId
	}
	return 0
}

type Z_C_LoginMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	Id         int64    `protobuf:"varint,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Pos        *Point3F `protobuf:"bytes,3,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Rotation   float32  `protobuf:"fixed32,4,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
}

func (x *Z_C_LoginMap) Reset() {
	*x = Z_C_LoginMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_LoginMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_LoginMap) ProtoMessage() {}

func (x *Z_C_LoginMap) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_LoginMap.ProtoReflect.Descriptor instead.
func (*Z_C_LoginMap) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{3}
}

func (x *Z_C_LoginMap) GetPacketHead() *Ipacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *Z_C_LoginMap) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Z_C_LoginMap) GetPos() *Point3F {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Z_C_LoginMap) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

type Z_C_ENTITY struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *Ipacket             `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	EntityInfo []*Z_C_ENTITY_Entity `protobuf:"bytes,2,rep,name=EntityInfo,proto3" json:"EntityInfo,omitempty"`
}

func (x *Z_C_ENTITY) Reset() {
	*x = Z_C_ENTITY{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY) ProtoMessage() {}

func (x *Z_C_ENTITY) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4}
}

func (x *Z_C_ENTITY) GetPacketHead() *Ipacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *Z_C_ENTITY) GetEntityInfo() []*Z_C_ENTITY_Entity {
	if x != nil {
		return x.EntityInfo
	}
	return nil
}

type C_Z_LoginCopyMap struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PacketHead *Ipacket `protobuf:"bytes,1,opt,name=PacketHead,proto3" json:"PacketHead,omitempty"`
	DataId     int32    `protobuf:"varint,2,opt,name=DataId,proto3" json:"DataId,omitempty"`
}

func (x *C_Z_LoginCopyMap) Reset() {
	*x = C_Z_LoginCopyMap{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_LoginCopyMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_LoginCopyMap) ProtoMessage() {}

func (x *C_Z_LoginCopyMap) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_LoginCopyMap.ProtoReflect.Descriptor instead.
func (*C_Z_LoginCopyMap) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{5}
}

func (x *C_Z_LoginCopyMap) GetPacketHead() *Ipacket {
	if x != nil {
		return x.PacketHead
	}
	return nil
}

func (x *C_Z_LoginCopyMap) GetDataId() int32 {
	if x != nil {
		return x.DataId
	}
	return 0
}

type C_Z_Move_Move struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mode   int32                 `protobuf:"varint,1,opt,name=Mode,proto3" json:"Mode,omitempty"`
	Normal *C_Z_Move_Move_Normal `protobuf:"bytes,2,opt,name=normal,proto3" json:"normal,omitempty"`
}

func (x *C_Z_Move_Move) Reset() {
	*x = C_Z_Move_Move{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_Move_Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_Move_Move) ProtoMessage() {}

func (x *C_Z_Move_Move) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_Move_Move.ProtoReflect.Descriptor instead.
func (*C_Z_Move_Move) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1, 0}
}

func (x *C_Z_Move_Move) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *C_Z_Move_Move) GetNormal() *C_Z_Move_Move_Normal {
	if x != nil {
		return x.Normal
	}
	return nil
}

type C_Z_Move_Move_Normal struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos      *Point3F `protobuf:"bytes,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Yaw      float32  `protobuf:"fixed32,2,opt,name=Yaw,proto3" json:"Yaw,omitempty"`
	Duration float32  `protobuf:"fixed32,3,opt,name=Duration,proto3" json:"Duration,omitempty"`
}

func (x *C_Z_Move_Move_Normal) Reset() {
	*x = C_Z_Move_Move_Normal{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *C_Z_Move_Move_Normal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*C_Z_Move_Move_Normal) ProtoMessage() {}

func (x *C_Z_Move_Move_Normal) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use C_Z_Move_Move_Normal.ProtoReflect.Descriptor instead.
func (*C_Z_Move_Move_Normal) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *C_Z_Move_Move_Normal) GetPos() *Point3F {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *C_Z_Move_Move_Normal) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *C_Z_Move_Move_Normal) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

type Z_C_ENTITY_Entity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64                        `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`      //唯一id
	Data  *Z_C_ENTITY_Entity_DataMask  `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`   //初始化信息
	Move  *Z_C_ENTITY_Entity_MoveMask  `protobuf:"bytes,3,opt,name=Move,proto3" json:"Move,omitempty"`   //移动
	Stats *Z_C_ENTITY_Entity_StatsMask `protobuf:"bytes,4,opt,name=Stats,proto3" json:"Stats,omitempty"` //基础属性
}

func (x *Z_C_ENTITY_Entity) Reset() {
	*x = Z_C_ENTITY_Entity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0}
}

func (x *Z_C_ENTITY_Entity) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Z_C_ENTITY_Entity) GetData() *Z_C_ENTITY_Entity_DataMask {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Z_C_ENTITY_Entity) GetMove() *Z_C_ENTITY_Entity_MoveMask {
	if x != nil {
		return x.Move
	}
	return nil
}

func (x *Z_C_ENTITY_Entity) GetStats() *Z_C_ENTITY_Entity_StatsMask {
	if x != nil {
		return x.Stats
	}
	return nil
}

type Z_C_ENTITY_Entity_DataMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type       int32                                     `protobuf:"varint,1,opt,name=Type,proto3" json:"Type,omitempty"`             //类型，player(9)，npc(5)
	RemoveFlag bool                                      `protobuf:"varint,2,opt,name=RemoveFlag,proto3" json:"RemoveFlag,omitempty"` //销毁状态
	NpcData    *Z_C_ENTITY_Entity_DataMask_NpcDataMask   `protobuf:"bytes,3,opt,name=NpcData,proto3" json:"NpcData,omitempty"`        //npc初始信息
	SpellData  *Z_C_ENTITY_Entity_DataMask_SpellDataMask `protobuf:"bytes,4,opt,name=SpellData,proto3" json:"SpellData,omitempty"`    //effect初始信息
}

func (x *Z_C_ENTITY_Entity_DataMask) Reset() {
	*x = Z_C_ENTITY_Entity_DataMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity_DataMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity_DataMask) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity_DataMask) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity_DataMask.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity_DataMask) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *Z_C_ENTITY_Entity_DataMask) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_DataMask) GetRemoveFlag() bool {
	if x != nil {
		return x.RemoveFlag
	}
	return false
}

func (x *Z_C_ENTITY_Entity_DataMask) GetNpcData() *Z_C_ENTITY_Entity_DataMask_NpcDataMask {
	if x != nil {
		return x.NpcData
	}
	return nil
}

func (x *Z_C_ENTITY_Entity_DataMask) GetSpellData() *Z_C_ENTITY_Entity_DataMask_SpellDataMask {
	if x != nil {
		return x.SpellData
	}
	return nil
}

type Z_C_ENTITY_Entity_MoveMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos             *Point3F `protobuf:"bytes,1,opt,name=Pos,proto3" json:"Pos,omitempty"`
	Rotation        float32  `protobuf:"fixed32,2,opt,name=Rotation,proto3" json:"Rotation,omitempty"`
	ForceUpdateFlag bool     `protobuf:"varint,3,opt,name=ForceUpdateFlag,proto3" json:"ForceUpdateFlag,omitempty"` //强制拉回
}

func (x *Z_C_ENTITY_Entity_MoveMask) Reset() {
	*x = Z_C_ENTITY_Entity_MoveMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity_MoveMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity_MoveMask) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity_MoveMask) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity_MoveMask.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity_MoveMask) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0, 1}
}

func (x *Z_C_ENTITY_Entity_MoveMask) GetPos() *Point3F {
	if x != nil {
		return x.Pos
	}
	return nil
}

func (x *Z_C_ENTITY_Entity_MoveMask) GetRotation() float32 {
	if x != nil {
		return x.Rotation
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_MoveMask) GetForceUpdateFlag() bool {
	if x != nil {
		return x.ForceUpdateFlag
	}
	return false
}

type Z_C_ENTITY_Entity_StatsMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	HP                int32 `protobuf:"varint,1,opt,name=HP,proto3" json:"HP,omitempty"`                                // 生命
	MP                int32 `protobuf:"varint,2,opt,name=MP,proto3" json:"MP,omitempty"`                                // 真气
	MaxHP             int32 `protobuf:"varint,3,opt,name=MaxHP,proto3" json:"MaxHP,omitempty"`                          // 最大生命
	MaxMP             int32 `protobuf:"varint,4,opt,name=MaxMP,proto3" json:"MaxMP,omitempty"`                          // 最大真气
	PhyDamage         int32 `protobuf:"varint,5,opt,name=PhyDamage,proto3" json:"PhyDamage,omitempty"`                  // 物理伤害
	PhyDefence        int32 `protobuf:"varint,6,opt,name=PhyDefence,proto3" json:"PhyDefence,omitempty"`                // 物理防御
	SplDamage         int32 `protobuf:"varint,7,opt,name=SplDamage,proto3" json:"SplDamage,omitempty"`                  // 法术伤害
	SplDefence        int32 `protobuf:"varint,8,opt,name=SplDefence,proto3" json:"SplDefence,omitempty"`                // 法术防御
	Heal              int32 `protobuf:"varint,9,opt,name=Heal,proto3" json:"Heal,omitempty"`                            // 治疗
	CriticalTimes     int32 `protobuf:"varint,10,opt,name=CriticalTimes,proto3" json:"CriticalTimes,omitempty"`         // 暴击全局百分比伤害倍数
	Critical          int32 `protobuf:"varint,11,opt,name=Critical,proto3" json:"Critical,omitempty"`                   // 暴击全局百分比几率
	AntiCriticalTimes int32 `protobuf:"varint,12,opt,name=AntiCriticalTimes,proto3" json:"AntiCriticalTimes,omitempty"` // 抗暴击全局百分比伤害倍数
	AntiCritical      int32 `protobuf:"varint,13,opt,name=AntiCritical,proto3" json:"AntiCritical,omitempty"`           // 防暴击全局百分比几率
	Dodge             int32 `protobuf:"varint,14,opt,name=Dodge,proto3" json:"Dodge,omitempty"`                         // 闪避全局百分比几率
	Hit               int32 `protobuf:"varint,15,opt,name=Hit,proto3" json:"Hit,omitempty"`                             // 命中全局百分比几率
}

func (x *Z_C_ENTITY_Entity_StatsMask) Reset() {
	*x = Z_C_ENTITY_Entity_StatsMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity_StatsMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity_StatsMask) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity_StatsMask) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity_StatsMask.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity_StatsMask) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0, 2}
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetHP() int32 {
	if x != nil {
		return x.HP
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetMP() int32 {
	if x != nil {
		return x.MP
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetMaxHP() int32 {
	if x != nil {
		return x.MaxHP
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetMaxMP() int32 {
	if x != nil {
		return x.MaxMP
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetPhyDamage() int32 {
	if x != nil {
		return x.PhyDamage
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetPhyDefence() int32 {
	if x != nil {
		return x.PhyDefence
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetSplDamage() int32 {
	if x != nil {
		return x.SplDamage
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetSplDefence() int32 {
	if x != nil {
		return x.SplDefence
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetHeal() int32 {
	if x != nil {
		return x.Heal
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetCriticalTimes() int32 {
	if x != nil {
		return x.CriticalTimes
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetCritical() int32 {
	if x != nil {
		return x.Critical
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetAntiCriticalTimes() int32 {
	if x != nil {
		return x.AntiCriticalTimes
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetAntiCritical() int32 {
	if x != nil {
		return x.AntiCritical
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetDodge() int32 {
	if x != nil {
		return x.Dodge
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_StatsMask) GetHit() int32 {
	if x != nil {
		return x.Hit
	}
	return 0
}

type Z_C_ENTITY_Entity_DataMask_NpcDataMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataId int32 `protobuf:"varint,1,opt,name=DataId,proto3" json:"DataId,omitempty"` //模板id
}

func (x *Z_C_ENTITY_Entity_DataMask_NpcDataMask) Reset() {
	*x = Z_C_ENTITY_Entity_DataMask_NpcDataMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity_DataMask_NpcDataMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity_DataMask_NpcDataMask) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity_DataMask_NpcDataMask) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity_DataMask_NpcDataMask.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity_DataMask_NpcDataMask) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0, 0, 0}
}

func (x *Z_C_ENTITY_Entity_DataMask_NpcDataMask) GetDataId() int32 {
	if x != nil {
		return x.DataId
	}
	return 0
}

type Z_C_ENTITY_Entity_DataMask_SpellDataMask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DataId   int32 `protobuf:"varint,1,opt,name=DataId,proto3" json:"DataId,omitempty"`     //特效id
	LifeTime int32 `protobuf:"varint,2,opt,name=LifeTime,proto3" json:"LifeTime,omitempty"` //存在事件
	FlySpeed int32 `protobuf:"varint,3,opt,name=FlySpeed,proto3" json:"FlySpeed,omitempty"` //飞行速度
}

func (x *Z_C_ENTITY_Entity_DataMask_SpellDataMask) Reset() {
	*x = Z_C_ENTITY_Entity_DataMask_SpellDataMask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_game_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Z_C_ENTITY_Entity_DataMask_SpellDataMask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Z_C_ENTITY_Entity_DataMask_SpellDataMask) ProtoMessage() {}

func (x *Z_C_ENTITY_Entity_DataMask_SpellDataMask) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Z_C_ENTITY_Entity_DataMask_SpellDataMask.ProtoReflect.Descriptor instead.
func (*Z_C_ENTITY_Entity_DataMask_SpellDataMask) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{4, 0, 0, 1}
}

func (x *Z_C_ENTITY_Entity_DataMask_SpellDataMask) GetDataId() int32 {
	if x != nil {
		return x.DataId
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_DataMask_SpellDataMask) GetLifeTime() int32 {
	if x != nil {
		return x.LifeTime
	}
	return 0
}

func (x *Z_C_ENTITY_Entity_DataMask_SpellDataMask) GetFlySpeed() int32 {
	if x != nil {
		return x.FlySpeed
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

var file_game_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x0d, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x07, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x46, 0x12,
	0x0c, 0x0a, 0x01, 0x58, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x58, 0x12, 0x0c, 0x0a,
	0x01, 0x59, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x59, 0x12, 0x0c, 0x0a, 0x01, 0x5a,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x5a, 0x22, 0x98, 0x02, 0x0a, 0x08, 0x43, 0x5f,
	0x5a, 0x5f, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x30, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0a, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x12, 0x2a, 0x0a, 0x04, 0x6d, 0x6f, 0x76, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x43, 0x5f, 0x5a, 0x5f, 0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x52, 0x04,
	0x6d, 0x6f, 0x76, 0x65, 0x1a, 0xad, 0x01, 0x0a, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4d, 0x6f, 0x64,
	0x65, 0x12, 0x35, 0x0a, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x43, 0x5f, 0x5a, 0x5f,
	0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x2e, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x52, 0x06, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x1a, 0x5a, 0x0a, 0x06, 0x4e, 0x6f, 0x72, 0x6d,
	0x61, 0x6c, 0x12, 0x22, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33,
	0x46, 0x52, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x59, 0x61, 0x77, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x03, 0x59, 0x61, 0x77, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x22, 0x73, 0x0a, 0x09, 0x43, 0x5f, 0x5a, 0x5f, 0x53, 0x6b, 0x69, 0x6c,
	0x6c, 0x12, 0x30, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x49, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x49, 0x64, 0x12, 0x1a, 0x0a,
	0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x49, 0x64, 0x22, 0x90, 0x01, 0x0a, 0x0c, 0x5a, 0x5f,
	0x43, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x4d, 0x61, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10,
	0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x52, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x03,
	0x50, 0x6f, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x33, 0x46, 0x52, 0x03, 0x50, 0x6f, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc4, 0x09, 0x0a,
	0x0a, 0x5a, 0x5f, 0x43, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x12, 0x30, 0x0a, 0x0a, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x70, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x52, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x12, 0x3a, 0x0a,
	0x0a, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x5a, 0x5f, 0x43, 0x5f,
	0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x0a, 0x45,
	0x6e, 0x74, 0x69, 0x74, 0x79, 0x49, 0x6e, 0x66, 0x6f, 0x1a, 0xc7, 0x08, 0x0a, 0x06, 0x45, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x49, 0x64, 0x12, 0x37, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x5a, 0x5f, 0x43,
	0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x37, 0x0a,
	0x04, 0x4d, 0x6f, 0x76, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x5a, 0x5f, 0x43, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59,
	0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x4d, 0x6f, 0x76, 0x65, 0x4d, 0x61, 0x73, 0x6b,
	0x52, 0x04, 0x4d, 0x6f, 0x76, 0x65, 0x12, 0x3a, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x73, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e,
	0x5a, 0x5f, 0x43, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74,
	0x79, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x73, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x05, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x1a, 0xe2, 0x02, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x6b, 0x12,
	0x12, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x6c, 0x61,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46,
	0x6c, 0x61, 0x67, 0x12, 0x49, 0x0a, 0x07, 0x4e, 0x70, 0x63, 0x44, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x2f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x5a,
	0x5f, 0x43, 0x5f, 0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x2e, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x6b, 0x2e, 0x4e, 0x70, 0x63, 0x44, 0x61, 0x74,
	0x61, 0x4d, 0x61, 0x73, 0x6b, 0x52, 0x07, 0x4e, 0x70, 0x63, 0x44, 0x61, 0x74, 0x61, 0x12, 0x4f,
	0x0a, 0x09, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x31, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x5a, 0x5f, 0x43, 0x5f,
	0x45, 0x4e, 0x54, 0x49, 0x54, 0x59, 0x2e, 0x45, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x4d, 0x61, 0x73, 0x6b, 0x2e, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61,
	0x4d, 0x61, 0x73, 0x6b, 0x52, 0x09, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x1a,
	0x25, 0x0a, 0x0b, 0x4e, 0x70, 0x63, 0x44, 0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x16,
	0x0a, 0x06, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x64, 0x1a, 0x5f, 0x0a, 0x0d, 0x53, 0x70, 0x65, 0x6c, 0x6c, 0x44,
	0x61, 0x74, 0x61, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x61, 0x74, 0x61, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x44, 0x61, 0x74, 0x61, 0x49, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x4c, 0x69, 0x66, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x4c, 0x69, 0x66, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x46,
	0x6c, 0x79, 0x53, 0x70, 0x65, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x46,
	0x6c, 0x79, 0x53, 0x70, 0x65, 0x65, 0x64, 0x1a, 0x74, 0x0a, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x4d,
	0x61, 0x73, 0x6b, 0x12, 0x22, 0x0a, 0x03, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x33, 0x46, 0x52, 0x03, 0x50, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x08, 0x52, 0x6f, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x0f, 0x46, 0x6f, 0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x46, 0x6f,
	0x72, 0x63, 0x65, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x46, 0x6c, 0x61, 0x67, 0x1a, 0xa3, 0x03,
	0x0a, 0x09, 0x53, 0x74, 0x61, 0x74, 0x73, 0x4d, 0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x48,
	0x50, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x48, 0x50, 0x12, 0x0e, 0x0a, 0x02, 0x4d,
	0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x4d, 0x50, 0x12, 0x14, 0x0a, 0x05, 0x4d,
	0x61, 0x78, 0x48, 0x50, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x4d, 0x61, 0x78, 0x48,
	0x50, 0x12, 0x14, 0x0a, 0x05, 0x4d, 0x61, 0x78, 0x4d, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x4d, 0x61, 0x78, 0x4d, 0x50, 0x12, 0x1c, 0x0a, 0x09, 0x50, 0x68, 0x79, 0x44, 0x61,
	0x6d, 0x61, 0x67, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x50, 0x68, 0x79, 0x44,
	0x61, 0x6d, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x50, 0x68, 0x79, 0x44, 0x65, 0x66, 0x65,
	0x6e, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x50, 0x68, 0x79, 0x44, 0x65,
	0x66, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x53, 0x70, 0x6c, 0x44, 0x61, 0x6d, 0x61,
	0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x53, 0x70, 0x6c, 0x44, 0x61, 0x6d,
	0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x70, 0x6c, 0x44, 0x65, 0x66, 0x65, 0x6e, 0x63,
	0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x70, 0x6c, 0x44, 0x65, 0x66, 0x65,
	0x6e, 0x63, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x6c, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x48, 0x65, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x43, 0x72, 0x69, 0x74, 0x69,
	0x63, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x2c, 0x0a, 0x11, 0x41, 0x6e, 0x74,
	0x69, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x11, 0x41, 0x6e, 0x74, 0x69, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63,
	0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x41, 0x6e, 0x74, 0x69, 0x43,
	0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x41,
	0x6e, 0x74, 0x69, 0x43, 0x72, 0x69, 0x74, 0x69, 0x63, 0x61, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x44,
	0x6f, 0x64, 0x67, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x44, 0x6f, 0x64, 0x67,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x48, 0x69, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x48, 0x69, 0x74, 0x22, 0x5c, 0x0a, 0x10, 0x43, 0x5f, 0x5a, 0x5f, 0x4c, 0x6f, 0x67, 0x69, 0x6e,
	0x43, 0x6f, 0x70, 0x79, 0x4d, 0x61, 0x70, 0x12, 0x30, 0x0a, 0x0a, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x48, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x2e, 0x49, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x0a, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x61, 0x74,
	0x61, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x44, 0x61, 0x74, 0x61, 0x49,
	0x64, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData = file_game_proto_rawDesc
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(file_game_proto_rawDescData)
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_game_proto_goTypes = []interface{}{
	(*Point3F)(nil),                                  // 0: message.Point3F
	(*C_Z_Move)(nil),                                 // 1: message.C_Z_Move
	(*C_Z_Skill)(nil),                                // 2: message.C_Z_Skill
	(*Z_C_LoginMap)(nil),                             // 3: message.Z_C_LoginMap
	(*Z_C_ENTITY)(nil),                               // 4: message.Z_C_ENTITY
	(*C_Z_LoginCopyMap)(nil),                         // 5: message.C_Z_LoginCopyMap
	(*C_Z_Move_Move)(nil),                            // 6: message.C_Z_Move.Move
	(*C_Z_Move_Move_Normal)(nil),                     // 7: message.C_Z_Move.Move.Normal
	(*Z_C_ENTITY_Entity)(nil),                        // 8: message.Z_C_ENTITY.Entity
	(*Z_C_ENTITY_Entity_DataMask)(nil),               // 9: message.Z_C_ENTITY.Entity.DataMask
	(*Z_C_ENTITY_Entity_MoveMask)(nil),               // 10: message.Z_C_ENTITY.Entity.MoveMask
	(*Z_C_ENTITY_Entity_StatsMask)(nil),              // 11: message.Z_C_ENTITY.Entity.StatsMask
	(*Z_C_ENTITY_Entity_DataMask_NpcDataMask)(nil),   // 12: message.Z_C_ENTITY.Entity.DataMask.NpcDataMask
	(*Z_C_ENTITY_Entity_DataMask_SpellDataMask)(nil), // 13: message.Z_C_ENTITY.Entity.DataMask.SpellDataMask
	(*Ipacket)(nil),                                  // 14: message.Ipacket
}
var file_game_proto_depIdxs = []int32{
	14, // 0: message.C_Z_Move.PacketHead:type_name -> message.Ipacket
	6,  // 1: message.C_Z_Move.move:type_name -> message.C_Z_Move.Move
	14, // 2: message.C_Z_Skill.PacketHead:type_name -> message.Ipacket
	14, // 3: message.Z_C_LoginMap.PacketHead:type_name -> message.Ipacket
	0,  // 4: message.Z_C_LoginMap.Pos:type_name -> message.Point3F
	14, // 5: message.Z_C_ENTITY.PacketHead:type_name -> message.Ipacket
	8,  // 6: message.Z_C_ENTITY.EntityInfo:type_name -> message.Z_C_ENTITY.Entity
	14, // 7: message.C_Z_LoginCopyMap.PacketHead:type_name -> message.Ipacket
	7,  // 8: message.C_Z_Move.Move.normal:type_name -> message.C_Z_Move.Move.Normal
	0,  // 9: message.C_Z_Move.Move.Normal.Pos:type_name -> message.Point3F
	9,  // 10: message.Z_C_ENTITY.Entity.Data:type_name -> message.Z_C_ENTITY.Entity.DataMask
	10, // 11: message.Z_C_ENTITY.Entity.Move:type_name -> message.Z_C_ENTITY.Entity.MoveMask
	11, // 12: message.Z_C_ENTITY.Entity.Stats:type_name -> message.Z_C_ENTITY.Entity.StatsMask
	12, // 13: message.Z_C_ENTITY.Entity.DataMask.NpcData:type_name -> message.Z_C_ENTITY.Entity.DataMask.NpcDataMask
	13, // 14: message.Z_C_ENTITY.Entity.DataMask.SpellData:type_name -> message.Z_C_ENTITY.Entity.DataMask.SpellDataMask
	0,  // 15: message.Z_C_ENTITY.Entity.MoveMask.Pos:type_name -> message.Point3F
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	file_message_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_game_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point3F); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_Skill); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_LoginMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_LoginCopyMap); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_Move_Move); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*C_Z_Move_Move_Normal); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity_DataMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity_MoveMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity_StatsMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity_DataMask_NpcDataMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_game_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Z_C_ENTITY_Entity_DataMask_SpellDataMask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_game_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_rawDesc = nil
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
