// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SERVICE int32

const (
	SERVICE_NONE          SERVICE = 0
	SERVICE_CLIENT        SERVICE = 1
	SERVICE_GATESERVER    SERVICE = 2
	SERVICE_ACCOUNTSERVER SERVICE = 3
	SERVICE_WORLDSERVER   SERVICE = 4
	SERVICE_ZONESERVER    SERVICE = 5
	SERVICE_WORLDDBSERVER SERVICE = 6
)

var SERVICE_name = map[int32]string{
	0: "NONE",
	1: "CLIENT",
	2: "GATESERVER",
	3: "ACCOUNTSERVER",
	4: "WORLDSERVER",
	5: "ZONESERVER",
	6: "WORLDDBSERVER",
}

var SERVICE_value = map[string]int32{
	"NONE":          0,
	"CLIENT":        1,
	"GATESERVER":    2,
	"ACCOUNTSERVER": 3,
	"WORLDSERVER":   4,
	"ZONESERVER":    5,
	"WORLDDBSERVER": 6,
}

func (x SERVICE) String() string {
	return proto.EnumName(SERVICE_name, int32(x))
}

func (SERVICE) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

type CHAT int32

const (
	CHAT_MSG_TYPE_WORLD   CHAT = 0
	CHAT_MSG_TYPE_PRIVATE CHAT = 1
	CHAT_MSG_TYPE_ORG     CHAT = 2
	CHAT_MSG_TYPE_COUNT   CHAT = 3
)

var CHAT_name = map[int32]string{
	0: "MSG_TYPE_WORLD",
	1: "MSG_TYPE_PRIVATE",
	2: "MSG_TYPE_ORG",
	3: "MSG_TYPE_COUNT",
}

var CHAT_value = map[string]int32{
	"MSG_TYPE_WORLD":   0,
	"MSG_TYPE_PRIVATE": 1,
	"MSG_TYPE_ORG":     2,
	"MSG_TYPE_COUNT":   3,
}

func (x CHAT) String() string {
	return proto.EnumName(CHAT_name, int32(x))
}

func (CHAT) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

type Ipacket struct {
	Stx                  int32    `protobuf:"varint,1,opt,name=Stx,proto3" json:"Stx,omitempty"`
	DestServerType       int32    `protobuf:"varint,2,opt,name=DestServerType,proto3" json:"DestServerType,omitempty"`
	Ckx                  int32    `protobuf:"varint,3,opt,name=Ckx,proto3" json:"Ckx,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=Id,proto3" json:"Id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ipacket) Reset()         { *m = Ipacket{} }
func (m *Ipacket) String() string { return proto.CompactTextString(m) }
func (*Ipacket) ProtoMessage()    {}
func (*Ipacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *Ipacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ipacket.Unmarshal(m, b)
}
func (m *Ipacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ipacket.Marshal(b, m, deterministic)
}
func (m *Ipacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ipacket.Merge(m, src)
}
func (m *Ipacket) XXX_Size() int {
	return xxx_messageInfo_Ipacket.Size(m)
}
func (m *Ipacket) XXX_DiscardUnknown() {
	xxx_messageInfo_Ipacket.DiscardUnknown(m)
}

var xxx_messageInfo_Ipacket proto.InternalMessageInfo

func (m *Ipacket) GetStx() int32 {
	if m != nil {
		return m.Stx
	}
	return 0
}

func (m *Ipacket) GetDestServerType() int32 {
	if m != nil {
		return m.DestServerType
	}
	return 0
}

func (m *Ipacket) GetCkx() int32 {
	if m != nil {
		return m.Ckx
	}
	return 0
}

func (m *Ipacket) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type PlayerData struct {
	PlayerID             int64    `protobuf:"varint,1,opt,name=PlayerID,proto3" json:"PlayerID,omitempty"`
	PlayerName           string   `protobuf:"bytes,2,opt,name=PlayerName,proto3" json:"PlayerName,omitempty"`
	PlayerGold           int32    `protobuf:"varint,3,opt,name=PlayerGold,proto3" json:"PlayerGold,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerData) Reset()         { *m = PlayerData{} }
func (m *PlayerData) String() string { return proto.CompactTextString(m) }
func (*PlayerData) ProtoMessage()    {}
func (*PlayerData) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *PlayerData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerData.Unmarshal(m, b)
}
func (m *PlayerData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerData.Marshal(b, m, deterministic)
}
func (m *PlayerData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerData.Merge(m, src)
}
func (m *PlayerData) XXX_Size() int {
	return xxx_messageInfo_PlayerData.Size(m)
}
func (m *PlayerData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerData.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerData proto.InternalMessageInfo

func (m *PlayerData) GetPlayerID() int64 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *PlayerData) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerData) GetPlayerGold() int32 {
	if m != nil {
		return m.PlayerGold
	}
	return 0
}

func init() {
	proto.RegisterEnum("message.SERVICE", SERVICE_name, SERVICE_value)
	proto.RegisterEnum("message.CHAT", CHAT_name, CHAT_value)
	proto.RegisterType((*Ipacket)(nil), "message.Ipacket")
	proto.RegisterType((*PlayerData)(nil), "message.PlayerData")
}

func init() { proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd) }

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 305 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0xcd, 0x4e, 0xc2, 0x40,
	0x14, 0x85, 0xe9, 0x0f, 0x3f, 0x5e, 0xa5, 0x8e, 0x37, 0x2e, 0x1a, 0x17, 0x86, 0xb0, 0x30, 0x84,
	0x85, 0x1b, 0x9f, 0xa0, 0x4e, 0x27, 0x75, 0x12, 0x9c, 0x92, 0xe9, 0x88, 0xd1, 0x0d, 0x19, 0x65,
	0xa2, 0x09, 0x10, 0x48, 0x69, 0x08, 0xbc, 0xbd, 0xe9, 0x50, 0x2a, 0xba, 0xeb, 0xf9, 0xee, 0xf9,
	0x72, 0x9a, 0x0c, 0x74, 0x97, 0x66, 0xb3, 0xd1, 0x5f, 0xe6, 0x7e, 0x9d, 0xaf, 0x8a, 0x15, 0xb6,
	0xab, 0xd8, 0x37, 0xd0, 0xe6, 0x6b, 0xfd, 0x39, 0x37, 0x05, 0x12, 0xf0, 0xb2, 0x62, 0x17, 0x3a,
	0x3d, 0x67, 0xd0, 0x94, 0xe5, 0x27, 0xde, 0x41, 0x10, 0x9b, 0x4d, 0x91, 0x99, 0x7c, 0x6b, 0x72,
	0xb5, 0x5f, 0x9b, 0xd0, 0xb5, 0xc7, 0x7f, 0xb4, 0x34, 0xe9, 0x7c, 0x17, 0x7a, 0x07, 0x93, 0xce,
	0x77, 0x18, 0x80, 0xcb, 0x67, 0xa1, 0xdf, 0x73, 0x06, 0x9e, 0x74, 0xf9, 0xac, 0xff, 0x0d, 0x30,
	0x5e, 0xe8, 0xbd, 0xc9, 0x63, 0x5d, 0x68, 0xbc, 0x81, 0xce, 0x21, 0xf1, 0xd8, 0xce, 0x79, 0xb2,
	0xce, 0x78, 0x7b, 0x6c, 0x0a, 0xbd, 0x3c, 0xec, 0x9d, 0xc9, 0x13, 0xf2, 0x7b, 0x4f, 0x56, 0x8b,
	0x59, 0x35, 0x79, 0x42, 0x86, 0x5b, 0x68, 0x67, 0x4c, 0x4e, 0x38, 0x65, 0xd8, 0x01, 0x5f, 0xa4,
	0x82, 0x91, 0x06, 0x02, 0xb4, 0xe8, 0x88, 0x33, 0xa1, 0x88, 0x83, 0x01, 0x40, 0x12, 0x29, 0x56,
	0x96, 0x98, 0x24, 0x2e, 0x5e, 0x41, 0x37, 0xa2, 0x34, 0x7d, 0x11, 0xaa, 0x42, 0x1e, 0x5e, 0xc2,
	0xf9, 0x6b, 0x2a, 0x47, 0x71, 0x05, 0xfc, 0xd2, 0x79, 0x4f, 0xc5, 0xd1, 0x69, 0x96, 0x8e, 0x2d,
	0xc4, 0x8f, 0x15, 0x6a, 0x0d, 0x27, 0xe0, 0xd3, 0xa7, 0x48, 0x21, 0x42, 0xf0, 0x9c, 0x25, 0x53,
	0xf5, 0x36, 0x66, 0x53, 0xdb, 0x21, 0x0d, 0xbc, 0x06, 0x52, 0xb3, 0xb1, 0xe4, 0x93, 0x48, 0x31,
	0xe2, 0x20, 0x81, 0x8b, 0x9a, 0xa6, 0x32, 0x21, 0xee, 0x1f, 0xd7, 0xfe, 0x11, 0xf1, 0x3e, 0x5a,
	0xf6, 0xc1, 0x1e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xe7, 0x5b, 0x31, 0x65, 0xc1, 0x01, 0x00,
	0x00,
}
